# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
//= require chartist

ready = ->
  $(document).ready ->
    $.ajax({
      url: window.location.href + "/results",
      dataType: 'json'
    }).success((results) ->
      responsiveOptions = [
        [
          'screen and (min-width: 640px)'
          {
            chartPadding: 30
            labelOffset: 100
            labelDirection: 'explode'
            labelInterpolationFnc: (value) ->
              value
          }
        ]
        [
          'screen and (min-width: 1024px)'
          {
            labelOffset: 120
            chartPadding: 20
          }
        ]
      ]
      new Chartist.Bar('.ct-chart', results, {
        seriesBarDistance: 10,
        reverseData: true,
        horizontalBars: true,
        axisY: {
          offset: 70
        }
      });
    );

$(document).on("ready page:load", ready);

# ---
# generated by js2coffee 2.0.0
